upgrade to phx 1.4
AgileVentures/sing_for_needs pull request #7
Opened 2019-01-27 06:31 UTC by harshdeepkanhai

Upgraded Phoenix from 1.3 to 1.4
Fixes #5

2019-02-16 19:30 UTC, FedericoEsparza requested changes
@harshdeepkanhai Great work so far!
 
I think you almost got it done. Your other PR for travis does have it passing CI.
 
However, the css isn't working.
<img width="345" alt="screenshot 2019-02-16 13 25 39" src="https://user-images.githubusercontent.com/11988089/52904233-15a5ae80-3221-11e9-89a7-36ecce363686.png">
 
I'll look into it more closely tomorrow, but I think this is related to what @aonomike was facing in the `championer_one` upgrade.

2019-02-18 23:09 UTC, wevtimoteo approved these changes

2019-02-25 20:58 UTC, FedericoEsparza approved these changes

2019-02-25 20:59 UTC, merged

2019-02-25 21:48 UTC, FedericoEsparza commented
@wevtimoteo @mattwr18 and @75pollet Excellent job sorting this out.

Thanks so much!

<img width="841" alt="screenshot 2019-02-25 14 55 10" src="https://user-images.githubusercontent.com/11988089/53370892-d543e000-3946-11e9-8beb-21dce3070c31.png">

We're back to good, plus we're done with Brunch!

Thanks again to @harshdeepkanhai for doing all the initial work. Great job!

Really appreciate it.